using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace Kursovaya
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public static int str;
        public static int col;
        private Random random = new Random();
        public DataTable inputTable { get; set; }
        public DataTable outputTable { get; set; }
        public MainWindow()
        {
            InitializeComponent();
        }
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            if (!Int32.TryParse(strField.Text, out str))
            {
                MessageBox.Show("Неверное значение строк");
                return;
            }
            if (!Int32.TryParse(colField.Text, out col))
            {
                MessageBox.Show("Неверное значение колонок");
                return;
            }

            // некоторые свойства для сетки
            // запретить сортировку столбцов
            matrix2.CanUserSortColumns = false;
            // выключить виртуализацию строк
            if (str < 20) matrix2.EnableRowVirtualization = false;
            matrix2.HorizontalContentAlignment = new HorizontalAlignment();

            int[,] arr = new int[str, col];

            // заполнение двумерного массива случайными числами
            for (int i = 0; i < str; i++)
            {
                for (int j = 0; j < col; j++)
                {
                    arr[i, j] = random.Next(1, 150);
                }
            }
            // заполнение DataTable данными из массива
            inputTable = Table.CreateDataTable(arr);
         
            outputTable = new DataTable();
            int b = 0;
            //создание DataTable на основе исходной, с пользовательским типом данных
            foreach (DataColumn column in inputTable.Columns)
            {
                ++b;
                outputTable.Columns.Add("c" + b, typeof(Cell));
            }
            //заполнение Table
            for (int i = 0; i < inputTable.Rows.Count; i++)
            {
                var row = outputTable.NewRow();
                var values = inputTable.Rows[i].ItemArray;
                SolidColorBrush colors = Brushes.Salmon;

                for (int j = 0; j < inputTable.Columns.Count; j++)
                {
                    Cell cell = new Cell(values[j] as string, colors);
                    row[j] = cell;
                }
                outputTable.Rows.Add(row);
            }

            matrix2.ItemsSource = outputTable.DefaultView;
        }
        void OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            DataTemplate dt = null;

            if (e.PropertyType == typeof(Cell))
                dt = (DataTemplate)Resources["GridCell"];

            if (dt != null)
            {
                DataGridTemplateColumn c = new DataGridTemplateColumn()
                {
                    CellTemplate = dt,
                    Header = e.Column.Header,
                    HeaderTemplate = e.Column.HeaderTemplate,
                    HeaderStringFormat = e.Column.HeaderStringFormat,
                    SortMemberPath = e.PropertyName
                };
                e.Column = c;
            }
        }
        private void SelectedCellsChanged(object sender, SelectedCellsChangedEventArgs e)
        {
            (sender as DataGrid).SelectionUnit = DataGridSelectionUnit.Cell;
            (sender as DataGrid).SelectedCells.Clear();
        }

        private void matrix2_AutoGeneratedColumns(object sender, EventArgs e)
        {
           
        }
    }
}